#!/usr/bin/env python3
"""
Generate dsdl_embedded.c from public_regulated_data_types .dsdl files.
Usage: embed_dsdl.py --dsdl-root <dir> --output <file.c> <path1> [path2 ...]
Paths are relative to --dsdl-root (e.g. reg/udral/physics/dynamics/rotation/Planar.0.1.dsdl).
"""
import argparse
import os


def c_escape(s: str) -> str:
    out = []
    for c in s:
        if c == "\\":
            out.append("\\\\")
        elif c == '"':
            out.append('\\"')
        elif c == "\n":
            out.append("\\n")
        elif c == "\r":
            continue
        elif ord(c) < 0x20:
            out.append("\\x%02x" % ord(c))
        else:
            out.append(c)
    return "".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dsdl-root", required=True, help="Root directory of public_regulated_data_types")
    ap.add_argument("--output", required=True, help="Output .c file path")
    ap.add_argument("paths", nargs="+", help="Relative paths to .dsdl files")
    args = ap.parse_args()
    root = os.path.normpath(args.dsdl_root)
    entries = []
    for rel in args.paths:
        full = os.path.normpath(os.path.join(root, rel))
        if not os.path.commonpath([root, full]) == root or not os.path.isfile(full):
            raise SystemExit("Missing or path escape: %s" % rel)
        with open(full, "r", encoding="utf-8", newline="") as f:
            body = f.read()
        path_for_c = rel.replace("\\", "/")
        body_escaped = c_escape(body)
        entries.append((path_for_c, body_escaped))
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as out:
        out.write("/* Generated by embed_dsdl.py - do not edit */\n\n")
        out.write('#include "dsdl_embedded.h"\n\n')
        out.write("const dsdl_embedded_entry_t dsdl_embedded_files[] = {\n")
        for path_c, body_c in entries:
            out.write('    { "%s",\n      "%s" },\n' % (path_c.replace('"', '\\"'), body_c))
        out.write("};\n\n")
        out.write("const size_t dsdl_embedded_count = sizeof(dsdl_embedded_files) / sizeof(dsdl_embedded_files[0]);\n")
    print("Generated %s (%u entries)" % (args.output, len(entries)))


if __name__ == "__main__":
    main()
